

# project:
#   type: website
#   output-dir: _site
#   
# website:
#   title: "Thea Portfolio Analytics"
#   favicon: logo.png
#   navbar:
#     logo: logo.png
#     logo-alt: "NAVcast Logo"
#     background: light
#         
#   page-footer:
#     center: |
#       Copyright 2025, NAVcast Module
#     background: light
#     
# format:
#   html:
#     theme: cosmo
#     css: navbar-custom.css
#     page-layout: full
#     toc: true
#     toc-depth: 5
#     toc-expand: 5
#     toc-location: left
#     toc-title: "Contents"
#     smooth-scroll: true
#     grid:
#       sidebar-width: 200px    # Narrower sidebar
#       body-width: 1100px      # Wider body
#       margin-width: 50px      # Smaller margins
#       gutter-width: 1rem      # Space between sidebar and content
#     
# execute:
#   echo: false
#   warning: false
#   
# resources:
#   - logo.png

project:
  type: website
  output-dir: _site
  
website:
  title: "Thea Portfolio Analytics"
  favicon: logo.png
  navbar:
    logo: logo.png
    logo-alt: "NAVcast Logo"
    background: light
        
  page-footer:
    center: |
      Copyright 2025, Thea Portfolio Analytics
    background: light
    
format:
  html:
    theme: cosmo
    css: navbar-custom.css
    page-layout: full
    toc: true
    toc-depth: 5
    toc-expand: 5
    toc-location: right
    toc-title: "Contents"
    
execute:
  echo: false
  warning: false
  
resources:
  - logo.png